#!/bin/bash

# modify variables here

TARGET_DIR="/home/miner"
BASE_DIR="$TARGET_DIR/miner-base"
CONFIG_FILE="$TARGET_DIR/.bfgminer/bfgminer.conf"
BASE_REPO="http://github.com/dzindra/miner-base.git"
BFGSTAT_REPO="http://github.com/dzindra/bfg-stats.git"
WIRINGPI_REPO="git://git.drogon.net/wiringPi"
USER_GROUP="miner:miner"

# install or update git repos
function checkGit {
	printf "Checking git repository $2/$3...\n";
	if [ -d "$2/$3" ]; then
		pushd "$2/$3" > /dev/null
		git pull
		popd > /dev/null
	else
		pushd "$2" > /dev/null
		git clone "$1" "$3"
		popd > /dev/null
		printf "Repository $3 cloned.\n";
	fi
}
checkGit "$BASE_REPO" "$TARGET_DIR" "miner-base"
checkGit "$BFGSTAT_REPO" "$TARGET_DIR" "bfg-stats"
checkGit "$WIRINGPI_REPO" "$TARGET_DIR" "wiringPi"


# cron entry
if cat /etc/crontab | grep "$BASE_DIR/run" >> /dev/null; then
	printf "Cron entry already created\n"
else
	printf "\n# attempt to start bfgminer if needed\n* *     * * *    miner   [ -x \"$BASE_DIR/run\" ] && \"$BASE_DIR/run\" -q\n\n" >> /etc/crontab
	printf "\n# advertise miner via upnp\n* *     * * *    miner   [ -x \"$BASE_DIR/upnp-beacon\" ] && \"$BASE_DIR/upnp-beacon\" -q -i eth0\n\n" >> /etc/crontab
fi


# apache site
if [ -e /etc/apache2/sites-available/bfg-stat ]; then
	printf "Apache2 site already created\n"
else
	ln -s "$BASE_DIR/apache-site" /etc/apache2/sites-available/bfg-stat
	# enable site and reload apache
	a2ensite bfg-stat && service apache2 reload
fi

# build and install wiringpi
if [ -e "$TARGET_DIR/wiringPi/gpio/gpio" ]; then
	printf "Wiringpi already compiled\n"
else
	pushd "$TARGET_DIR/wiringPi" > /dev/null
	./build
	popd > /dev/null
fi

# copy base config file
if [ -e "$CONFIG_FILE" ]; then
	printf "Config file already copied\n";
else
	CONFIG_DIR=`dirname "$CONFIG_FILE"`
	mkdir -p "$CONFIG_DIR"
	cp "$BASE_DIR/bfgminer.json" "$CONFIG_FILE"
	chown -R "$USER_GROUP" "$CONFIG_DIR"
	printf "Config file copied\n";
fi

printf "Blinking LED\n"
gpio mode 0 out
gpio write 0 1;sleep 0.2
gpio write 0 0;sleep 0.2
gpio write 0 1;sleep 0.2
gpio write 0 0;sleep 0.2
gpio write 0 1;sleep 0.2
gpio write 0 0
